name: Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          rustup update stable
          rustup target install wasm32-unknown-unknown
          cargo install wasm-pack
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          wasm-pack build --target web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "web"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
